//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagamentCompanyDiplom.ModelBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payments
    {
        public int ID_Payments { get; set; }
        public Nullable<System.DateTime> PaymentPeriod { get; set; }
        public Nullable<decimal> Sum { get; set; }
        public Nullable<System.DateTime> DataPayments { get; set; }
        public Nullable<int> ID_Accruals { get; set; }
    
        public virtual Accruals Accruals { get; set; }
    }
}
